### ISSUE TITLE
Mistake in naming

### ISSUE THREAD

**Issue by ivanternovyi** [Roman6917/Inheritance#2]
https://github.com/Roman6917/Inheritance/blob/53a652a78ba6606d9a7da606f8ec85f52fb7cd68/Inheritance/Classes/Parallelepiped.cs#L7

**Comment by Roman6917** [comment]
we used this name convention for variable like: width, length, etc.

**Comment by ivanternovyi** [comment]
'hight' is not correct, it should be 'height'
