### ISSUE TITLE
Variable height may be negative

### ISSUE THREAD

**Issue by ivanternovyi** [Roman6917/Inheritance#3]
You do not make any checks. May be you wanted to assign it to the property, which has necessary checks.
But it`s better to assign to a field inside the class.

https://github.com/Roman6917/Inheritance/blob/53a652a78ba6606d9a7da606f8ec85f52fb7cd68/Inheritance/Classes/Cylinder.cs#L24

**Comment by Roman6917** [comment]
we have setter, wich checks if height is positive

**Comment by ivanternovyi** [comment]
Setter is in the property, but you assign a variable directly to the field.

**Comment by Roman6917** [comment]
we assign value in constructor to our properties, so we don't need to check it one more time

**Comment by ivanternovyi** [comment]
I saw it, but in the Cylinder.cs you assigned it to the field. So that i have attached link of the code.
